# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'SKYYTextPractise' do
pod 'hpple', '~> 0.2.0'
pod 'YYText', '~> 1.0.5'
pod 'Masonry', '~> 1.0.1'
pod 'LGAlertView', '~> 2.0.13'
pod 'MWFeedParser'
pod 'UIImage+SVG', '~> 0.1'
end

