# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
target 'SKVideoPlayer' do
    
pod 'AFNetworking', '~> 3.2.1'
pod 'CocoaHTTPServer', '~> 2.3'
pod 'Masonry', '~> 1.1.0'
pod 'JDStatusBarNotification'
pod 'SDWebImage', '~> 4.4.1'
end
